FROM cronfy/lamp7.2-lik

COPY ./docker/conf/mysql.conf.d/ /etc/mysql/mysql.conf.d/
COPY ./docker/conf/php.conf.d/ /etc/php/7.2/apache2/conf.d/
COPY ./docker/conf/php.conf.d/ /etc/php/7.2/cli/conf.d/



